routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('clientes', 'ClienteController')->middleware('auth');
Route::resource('productos', 'ProductoController')->middleware('auth');

app/Cliente.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cliente extends Model
{
    protected $fillable = [
        'cedula',
        'nombre',
        'apellido',
        'telefono',
        'email',
        'fecha_nacimiento',
        'estatus'
    ];
}

app/Http/Controllers/ClienteController.php
<?php
namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Cliente;

class ClienteController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $clientes = Cliente::all();
        foreach ($clientes as $i => $cliente) {
            $cliente->estatus = strtoupper($cliente->estatus);
            $cliente->fecha_nacimiento = date('d/m/Y', strtotime($cliente->fecha_nacimiento));
            $clientes[$i] = $cliente;
        }
        
        $ruta = explode("/", $request->path());
        if ($ruta[0] == "api") {
            return response()->json(compact('clientes'), 201);
        } else {
            return view('clientes.index', compact('clientes'));
        }       
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('clientes.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'cedula' => 'required|numeric',
            'nombre' => 'required|between:2,20',
            'apellido' => 'required|between:2,20',
            'telefono' => 'required|between:7,50',
            'email' => 'required|email',
            'fecha_nacimiento' => 'required|date_format:"d/m/Y"',
            'estatus' => 'required'
        ]);
        $cliente = new Cliente([
            'cedula' => $request->get('cedula'),
            'nombre' => $request->get('nombre'),
            'apellido' => $request->get('apellido'),
            'telefono' => $request->get('telefono'),
            'email' => $request->get('email'),
            'fecha_nacimiento' => date('Y-m-d', strtotime(str_replace('/', '-', $request->get('fecha_nacimiento')))),
            'estatus' => $request->get('estatus')
        ]);
        $cliente->save();
        $ruta = explode("/", $request->path());
        if ($ruta[0] == "api") {
            return response()->json([
                'message' => '¡Cliente registrado!'
            ]);
        } else {
            return redirect('/clientes')->with('success', '¡Cliente registrado!');
        }        
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, $id)
    {
        $cliente = Cliente::find($id);
        $cliente->fecha_nacimiento = date('d/m/Y', strtotime($cliente->fecha_nacimiento));        
        $ruta = explode("/", $request->path());
        if ($ruta[0] == "api") {
            return response()->json(compact('cliente'), 201);
        } else {
            return null;
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $cliente = Cliente::find($id);
        $cliente->fecha_nacimiento = date('d/m/Y', strtotime($cliente->fecha_nacimiento));
        return view('clientes.edit', compact('cliente'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'cedula' => 'required|numeric',
            'nombre' => 'required|between:2,20',
            'apellido' => 'required|between:2,20',
            'telefono' => 'required|between:7,50',
            'email' => 'required|email',
            'fecha_nacimiento' => 'required|date_format:"d/m/Y"',
            'estatus' => 'required'
        ]);
        $cliente = Cliente::find($id);
        $cliente->cedula = $request->get('cedula');
        $cliente->nombre = $request->get('nombre');
        $cliente->apellido = $request->get('apellido');
        $cliente->telefono = $request->get('telefono');
        $cliente->email = $request->get('email');
        $cliente->fecha_nacimiento = date('Y-m-d', strtotime(str_replace('/', '-', $request->get('fecha_nacimiento'))));
        $cliente->estatus = $request->get('estatus');
        $cliente->save();
        $ruta = explode("/", $request->path());
        if ($ruta[0] == "api") {
            return response()->json([
                'message' => '¡Cliente actualizado!'
            ]);
        } else {
            return redirect('/clientes')->with('success', '¡Cliente actualizado!');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        $cliente = Cliente::find($id);
        $cliente->delete();
        $ruta = explode("/", $request->path());
        if ($ruta[0] == "api") {
            return response()->json([
                'message' => '¡Cliente eliminado!'
            ]);
        } else {
            return redirect('/clientes')->with('success', '¡Cliente eliminado!');
        }
        
    }
}

resources/views/clientes/create.blade.php
@extends('layouts.app')

@section('datepicker')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/css/bootstrap-datepicker.css" rel="stylesheet">

  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/js/bootstrap-datepicker.js"></script>
    <!-- Languaje -->
    <script src="{{asset('js/bootstrap-datepicker.es.min.js')}}"></script>
@endsection

@section('content')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Agregar un cliente</h1>
  <div>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('clientes.store') }}">
          @csrf
          <div class="form-group">    
              <label for="cedula">Cédula:</label>
              <input type="number" class="form-control" min="0" max="40000000" name="cedula"/>
          </div>
          <div class="form-group">
              <label for="nombre">Nombre:</label>
              <input type="text" class="form-control" name="nombre"/>
          </div>
          <div class="form-group">
              <label for="apellido">Apellido:</label>
              <input type="text" class="form-control" name="apellido"/>
          </div>
          <div class="form-group">
              <label for="telefono">Teléfono:</label>
              <input type="text" class="form-control" name="telefono"/>
          </div>
          <div class="form-group">
              <label for="email">Correo electrónico:</label>
              <input type="text" class="form-control" name="email"/>
          </div>
          <div class="form-group">
              <label for="fecha_nacimiento">Fecha de nacimiento (DD/MM/AAAA):</label>
              <input type="text" class="form-control datepicker" name="fecha_nacimiento"/>
          </div>
          <div class="form-group">
              <label for="estatus">Estatus:</label>
              <select class="form-control" name="estatus">
                 <option value="activo">Activo</option>
                 <option value="inactivo">Inactivo</option>
              </select>
          </div>                         
          <button type="submit" class="btn btn-primary-outline">Agregar cliente</button>
      </form>
  </div>
</div>
</div>
@endsection

@section('script')
<script>
    $('.datepicker').datepicker({  
       format: "dd/mm/yyyy",
       language: "es",
       autoclose: true
     });
</script>
@endsection

resources/views/clientes/edit.blade.php
@extends('layouts.app')

@section('datepicker')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/css/bootstrap-datepicker.css" rel="stylesheet">

  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/js/bootstrap-datepicker.js"></script>
    <!-- Languaje -->
    <script src="{{asset('js/bootstrap-datepicker.es.min.js')}}"></script>
@endsection

@section('content')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-3">Actualizar un cliente</h1>

        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br /> 
        @endif
        <form method="post" action="{{ route('clientes.update', $cliente->id) }}">
            @method('PATCH') 
            @csrf
              <div class="form-group">    
                  <label for="cedula">Cédula:</label>
                  <input type="number" class="form-control" name="cedula" min="0" max="40000000" value="{{ $cliente->cedula }}" />
              </div>
              <div class="form-group">
                  <label for="nombre">Nombre:</label>
                  <input type="text" class="form-control" name="nombre" value="{{ $cliente->nombre }}" />
              </div>
              <div class="form-group">
                  <label for="apellido">Apellido:</label>
                  <input type="text" class="form-control" name="apellido" value="{{ $cliente->apellido }}" />
              </div>
              <div class="form-group">
                  <label for="telefono">Teléfono:</label>
                  <input type="text" class="form-control" name="telefono" value="{{ $cliente->telefono }}" />
              </div>
              <div class="form-group">
                  <label for="email">Correo electrónico:</label>
                  <input type="text" class="form-control" name="email" value="{{ $cliente->email }}" />
              </div>
              <div class="form-group">
                  <label for="fecha_nacimiento">Fecha de nacimiento (DD/MM/AAAA):</label>
                  <input type="text" class="form-control datepicker" name="fecha_nacimiento" value="{{ $cliente->fecha_nacimiento }}" />
              </div>
              <div class="form-group">
                  <label for="estatus">Estatus:</label>
                  <select class="form-control" name="estatus">
                    <option value="activo" {{ ( $cliente->estatus == "activo") ? 'selected' : '' }}>Activo</option>
                    <option value="inactivo" {{ ( $cliente->estatus == "inactivo" ) ? 'selected' : '' }}>Inactivo</option>
                  </select>
              </div>
            <button type="submit" class="btn btn-primary">Actualizar</button>
        </form>
    </div>
</div>
@endsection

@section('script')
<script>
    $('.datepicker').datepicker({  
       format: "dd/mm/yyyy",
       language: "es",
       autoclose: true
     });
</script>
@endsection

resources/views/clientes/index.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
<div class="col-sm-12">
    <h1 class="display-3">Clientes</h1>    

<div>
    <a style="margin: 19px;" href="{{ route('clientes.create')}}" class="btn btn-primary">Nuevo cliente</a>
    </div>  

  <table class="table table-striped">
    <thead>
        <tr>
          <td>ID</td>
          <td>Cédula</td>
          <td>Nombre y Apellido</td>
          <td>Teléfono</td>
          <td>Correo electrónico</td>
          <td>Fecha de nacimiento</td>
          <td>Estatus</td>
          <td colspan = 2>Actions</td>
        </tr>
    </thead>
    <tbody>
        @foreach($clientes as $cliente)
        <tr>
            <td>{{$cliente->id}}</td>
            <td>{{$cliente->cedula}}</td>
            <td>{{$cliente->nombre}} {{$cliente->apellido}}</td>
            <td>{{$cliente->telefono}}</td>
            <td>{{$cliente->email}}</td>
            <td>{{$cliente->fecha_nacimiento}}</td>
            <td>{{$cliente->estatus}}</td>
            <td>
                <a href="{{ route('clientes.edit',$cliente->id)}}" class="btn btn-primary">Modificar</a>
            </td>
            <td>
                <form action="{{ route('clientes.destroy', $cliente->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Eliminar</button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
<div>
<div class="col-sm-12">

  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div>
  @endif
</div>
</div>
@endsection