routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('clientes', 'ClienteController')->middleware('auth');
Route::resource('productos', 'ProductoController')->middleware('auth');

app/Producto.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Producto extends Model
{
    protected $fillable = [
        'cantidad',
        'nombre',
        'descripcion',
        'precio_unitario',
        'estatus',
        'ruta_imagen'       
    ];
}

app/Http/Controllers/ProductoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Producto;

class ProductoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $productos = Producto::all();
        foreach ($productos as $i=>$producto) {
            $producto->estatus = strtoupper($producto->estatus);
            $productos[$i] = $producto;
        }
        
        $ruta = explode("/", $request->path());
        if ($ruta[0] == "api") {
            return response()->json(compact('productos'), 201);
        } else {
            return view('productos.index', compact('productos'));
        }      
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('productos.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'cantidad'=>'required|numeric',
            'descripcion'=>'between:0,500',
            'nombre'=>'required|between:2,150',
            'precio_unitario'=>'required|numeric',
            'estatus'=>'required'
        ]);
        $path = null;
        if ($request->hasFile('ruta_imagen')) {
            $path = $request->ruta_imagen->store('producto');
        }    
        $producto = new Producto([
            'cantidad' => $request->get('cantidad'),
            'nombre' => $request->get('nombre'),
            'descripcion' => $request->get('descripcion'),
            'precio_unitario' => $request->get('precio_unitario'),
            'estatus' => $request->get('estatus'),
            'ruta_imagen' => $path
        ]);

        $producto->save();
        $ruta = explode("/", $request->path());
        if ($ruta[0] == "api") {
            return response()->json([
                'message' => '¡Producto registrado!'
            ]);
        } else {
            return redirect('/productos')->with('success', '¡Producto registrado!');
        }             
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, $id)
    {
        //
        $producto = Producto::find($id);
        $ruta = explode("/", $request->path());
        if ($ruta[0] == "api") {
            return response()->json(compact('producto'), 201);
        } else {
            return null;
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $producto = Producto::find($id);
        return view('productos.edit', compact('producto'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'cantidad'=>'required|numeric',
            'descripcion'=>'between:0,500',
            'nombre'=>'required|between:2,150',
            'precio_unitario'=>'required|numeric',
            'estatus'=>'required'
        ]);
        $path = null;
        if ($request->hasFile('ruta_imagen')) {
            $path = $request->ruta_imagen->store('producto');
        } 
        $producto = Producto::find($id);
        $producto->cantidad =  $request->get('cantidad');
        $producto->nombre =  $request->get('nombre');
        $producto->descripcion =  $request->get('descripcion');
        $producto->precio_unitario =  $request->get('precio_unitario');
        $producto->estatus =  $request->get('estatus');
        if ($path != null) {
            $producto->ruta_imagen = $path;
        }
        $producto->save();
        $ruta = explode("/", $request->path());
        if ($ruta[0] == "api") {
            return response()->json([
                'message' => '¡Producto actualizado!'
            ]);
        } else {
            return redirect('/productos')->with('success', '¡Producto actualizado!');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        $producto = Producto::find($id);
        $producto->delete();
        $ruta = explode("/", $request->path());
        if ($ruta[0] == "api") {
            return response()->json([
                'message' => '¡Producto eliminado!'
            ]);
        } else {
            return redirect('/productos')->with('success', '¡Producto eliminado!');
        }
    }
}

resources/views/productos/create.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Agregar un producto</h1>
  <div>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('productos.store') }}" enctype="multipart/form-data">
          @csrf
          <div class="form-group">    
              <label for="cantidad">Cantidad:</label>
              <input type="number" class="form-control" name="cantidad" min="0" max="40000000"/>
          </div>
          <div class="form-group">
              <label for="nombre">Nombre:</label>
              <input type="text" class="form-control" name="nombre"/>
          </div>
          <div class="form-group">
              <label for="descripcion">Descripción:</label>
              <input type="text" class="form-control" name="descripcion"/>
          </div>
          <div class="form-group">
              <label for="precio_unitario">Precio Unitario:</label>
              <input type="text" class="form-control" name="precio_unitario"/>
          </div>
          <div class="form-group">
              <label for="estatus">Estatus:</label>
              <select class="form-control" name="estatus">
                 <option value="activo">Activo</option>
                 <option value="inactivo">Inactivo</option>
              </select>
          </div>
          <div class="form-group">
              <label for="ruta_imagen">Imagen:</label>
              <input type="file" class="form-control" name="ruta_imagen"/>
          </div>
          <button type="submit" class="btn btn-primary-outline">Agregar producto</button>
      </form>
  </div>
</div>
</div>
@endsection

resources/views/productos/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-3">Actualizar un producto</h1>

        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br /> 
        @endif
        <form method="post" action="{{ route('productos.update', $producto->id) }}" enctype="multipart/form-data">
            @method('PATCH') 
            @csrf
              <div class="form-group">    
                  <label for="cantidad">Cantidad:</label>
                  <input type="number" class="form-control" name="cantidad" value="{{ $producto->cantidad }}" min="0" max="40000000"/>
              </div>
              <div class="form-group">
                  <label for="nombre">Nombre:</label>
                  <input type="text" class="form-control" name="nombre" value="{{ $producto->nombre }}" />
              </div>
              <div class="form-group">
                  <label for="descripcion">Descripción:</label>
                  <input type="text" class="form-control" name="descripcion" value="{{ $producto->descripcion }}" />
              </div>
              <div class="form-group">
                  <label for="precio_unitario">Precio Unitario:</label>
                  <input type="text" class="form-control" name="precio_unitario" value="{{ $producto->precio_unitario }}" />
              </div>
              <div class="form-group">
                  <label for="estatus">Estatus:</label>
                  <select class="form-control" name="estatus">
                    <option value="activo" {{ ( $producto->estatus == "activo") ? 'selected' : '' }}>Activo</option>
                    <option value="inactivo" {{ ( $producto->estatus == "inactivo" ) ? 'selected' : '' }}>Inactivo</option>
                  </select>
              </div>
              <div class="form-group">
                  <label for="ruta_imagen">Imagen:</label>
                  <img src="{{ url('storage/'.$producto->ruta_imagen) }}" alt="" title="" height="100px"/>
                  <input type="file" class="form-control" name="ruta_imagen"/>
              </div>
            <button type="submit" class="btn btn-primary">Actualizar</button>
        </form>
    </div>
</div>
@endsection

resources/views/productos/index.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
<div class="col-sm-12">
    <h1 class="display-3">Productos</h1>    

<div>
    <a style="margin: 19px;" href="{{ route('productos.create')}}" class="btn btn-primary">Nuevo producto</a>
    </div>  

  <table class="table table-striped">
    <thead>
        <tr>
          <td>ID</td>
          <td>Cantidad</td>
          <td>Nombre</td>
          <td>Descripción</td>
          <td>Precio Unitario</td>
          <td>Estatus</td>
          <td>Imagen</td>
          <td colspan = 2>Actions</td>
        </tr>
    </thead>
    <tbody>
        @foreach($productos as $producto)
        <tr>
            <td>{{$producto->id}}</td>
            <td>{{$producto->cantidad}}</td>
            <td>{{$producto->nombre}}</td>
            <td>{{$producto->descripcion}}</td>
            <td>{{$producto->precio_unitario}}</td>
            <td>{{$producto->estatus}}</td>
            <td><img src="{{ url('storage/'.$producto->ruta_imagen) }}" alt="" title="" height="100px"/>  </td>
            <td>
                <a href="{{ route('productos.edit',$producto->id)}}" class="btn btn-primary">Modificar</a>
            </td>
            <td>
                <form action="{{ route('productos.destroy', $producto->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Eliminar</button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
<div>
<div class="col-sm-12">

  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div>
  @endif
</div>
</div>
@endsection